services:
  - type: web
    name: ai-powered-git-activity-monitor
    env: node
    buildCommand: |
      echo "=== BUILD START ==="
      echo "Node version: $(node --version)"
      echo "NPM version: $(npm --version)"
      pwd
      ls -la
      echo "=== INSTALLING ROOT DEPS ==="
      npm install
      echo "=== CLIENT BUILD ==="
      cd client
      echo "Client directory: $(pwd)"
      ls -la
      echo "=== INSTALLING CLIENT DEPS ==="
      npm install
      echo "=== RUNNING BUILD ==="
      npm run build
      echo "=== BUILD VERIFICATION ==="
      ls -la
      if [ -d "dist" ]; then
        echo "✅ Dist directory exists"
        ls -la dist/
      else
        echo "❌ Dist directory missing"
      fi
      cd ..
      echo "=== FINAL CHECK ==="
      ls -la client/
      if [ -d "client/dist" ]; then
        echo "✅ client/dist exists"
        ls -la client/dist/
      else
        echo "❌ client/dist missing"
      fi
      echo "=== BUILD END ==="
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 