services:
  - type: web
    name: ai-powered-git-activity-monitor
    env: node
    buildCommand: |
      echo "=== BUILD START ==="
      pwd
      ls -la
      npm install
      echo "=== CLIENT BUILD ==="
      cd client
      ls -la
      npm install
      npm run build
      echo "=== BUILD VERIFICATION ==="
      ls -la
      ls -la dist/
      cd ..
      echo "=== FINAL CHECK ==="
      ls -la client/dist/
      echo "=== BUILD END ==="
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 