services:
  - type: web
    name: ai-powered-git-activity-monitor
    env: node
    buildCommand: |
      echo "=== BUILD START ==="
      pwd
      ls -la
      npm install
      echo "=== CLIENT BUILD TEST ==="
      cd client
      node build-test.js
      echo "=== BUILD END ==="
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 